"""another-retry

Revision ID: 364d1300f164
Revises: 014a007cc6b4
Create Date: 2023-12-13 16:28:45.349054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364d1300f164'
down_revision: Union[str, None] = '014a007cc6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genrers')
    op.add_column('books', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.drop_column('books', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'genre_id')
    op.create_table('genrers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
