"""retry

Revision ID: 73c0d59701a0
Revises: a3dfa8d76a57
Create Date: 2023-12-13 15:07:58.151220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c0d59701a0'
down_revision: Union[str, None] = 'a3dfa8d76a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('best_seller', sa.String(), nullable=True))
    op.drop_column('authors', 'best_saler')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('best_saler', sa.VARCHAR(), nullable=True))
    op.drop_column('authors', 'best_seller')
    # ### end Alembic commands ###
